on:
  push:
    branches:
      - vscode
      - release/*
  pull_request:

name: Run Tests

jobs:

  test:
    name: Tests
    strategy:
        matrix:
          node: [14]
          os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}

      - run: yarn

      - run: yarn test
